---
gateway : "192.168.1.1"
dns: "192.168.1.148"
number_of_machines: "3"

vms_to_create:
 #- name: "Front"
 #  ip_address:  "192.168.1.200/24"
 #  memory: "1024"
 #  cores: "1"
 #  storage: "syn"
 #  node: "proxmox"
 #  clone: "Ubuntu-img1"
  
 #- name: "Back1"
 #  ip_address:  "192.168.1.201/24"
 #  memory: "2048"
 #  cores: "2"
 #  storage: "nvme"
 #  node: "pve"
 #  clone: "Ubuntu-img"

# - name: "Back2"
#   ip_address:  "192.168.1.202/24"
#   memory: "2048"
#   cores: "2"
#   storage: "nvme"
#   node: "pve"
#   clone: "Ubuntu-img"

 - name: "Main"
   ip_address:  "192.168.1.210/24"
   memory: "1024"
   cores: "1"
   storage: "nvme"
   node: "pve"
   clone: "Ubuntu-img"

# - name: "Repl"
#   ip_address:  "192.168.1.211/24"
#   memory: "1024"
#   cores: "1"
#   storage: "labs"
#   node: "proxmox"
#   clone: "Ubuntu-img1"
  
# - name: "MonLog"
#   ip_address:  "192.168.1.230/24"
#   memory: "8192"
#   cores: "3"
#   storage: "nvme"
#   node: "pve"
#   clone: "Ubuntu-img"

# - name: "Backup"
#   ip_address:  "192.168.1.240/24"
#   memory: "1024"
#   cores: "1"
#   storage: "syn"
#   node: "proxmox"
#   clone: "Ubuntu-img1"  


    