$ANSIBLE_VAULT;1.1;AES256
30386630333236623938333362626337643838373938656534323266373530323561373434656163
3161353834636435323463633866356638356434323665370a656534663964373832366133353534
65323833393933663830346130643663383233356236346632636134393639656537626138343062
3031343235623961640a333866363232326534313230323136373962353932333464383532376463
39303064336461376331383232643735313535646436376236393962383633333764623136373030
39633239666365383065633163353365323866323362313334346237656465303130323732616166
39376663316363323231363665626139393039383835653937663430353763346564643763653436
37663335316464323263383631336538346234663437373865653432383938376665666638336262
66623865366265356438663663656263633464656265346261376163663138663063356636626138
39373463386561666463613636303065613635363162373661643261373432623964666236346535
64336666633630643431613665613832343162666566333334616366636362656432616361373832
30626463303363303432356433373034383938356536336138373530326462346234323331383063
61626161633564633332333066383632366534366262303132346535386365326436653765356462
66353630626133653737643234623333383330643732653864386531383336376666633631353837
33643537356231306238643239376431626431393734333930383461323635616166393037653462
36636331376265356632623766663961373533653661666134373039303963393639393832356330
65323737306536626139656662626530623231326332353863656535656166653433343061616566
62313066353730323730313833633763393562383162376361336132613632333263383237343764
61383031393833383831633433633133353037306531613765643633383565366530373332656363
32353961363364646665386163316364313638336531663138373736373465623439363236353539
63633338623530313762386336333434323737643639396632633637306432616439643637386135
38363035613061373831623062626231626436323861626234636332343331366663613032346236
66666165363264323063366132653634643133643237656336663637653235383631616536363537
31363265383435353535353338386162303536363133643234386439353466313232653730653335
34326334346165303936623639303937613463626538633039346635666366653432623336363537
62393338316330333130383034316134343933393464626635666465333766353561333363363265
63656637316531313734396335343434353063383234346266376662306630366637363966633933
36316161633433366433326238363837323935666162333762623838306533333035653936643837
30613730656639313239653032303963663534306337643363313230366138386338656362363430
35336464656330313232653265376338623632616137646663363135396334323231333432353933
32366131356364336336646437653634313266363838353834343635393036393236306331633831
64313861613461663939316562343632663238643637666636376139656431396433396164623536
6234
